baseURL = "/"
title = "Andrew's Space" # ä½ çš„ç¶²ç«™åç¨±

[params]
  description = "Exploring Toys & Academic Papers"
  custom_css = ["css/style.css"]

[[menu.main]]
  name = "ğŸ§¸ Toys"
  url = "/toys"
  weight = 1

[[menu.main]]
  name = "ğŸ“„ Papers"
  url = "/papers"
  weight = 2